import Head from 'next/head'
import Career from '../components/career/Career'
import Contacts from '../components/contacts/Contacts'
import Footer from '../components/footer/Footer'
import Navbar from '../components/nav/navbar'
import Profile from '../components/profile/Profile'
import Projects from '../components/projects/Projects'
import Skills from '../components/skills/Skills'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Madjid Boudis - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Profile />
        <Skills />
        <Projects />
        <Career />
        <Contacts />
        <Footer />
        <Navbar />
      </main>
    </div>
  )
}
